package com.hcc.crest.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Data;

@Data
@TableName("service_card_type")
public class ServiceCardType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_card_type.id
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    @TableId(value= "id",type = IdType.AUTO)
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_card_type.app_code
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    @TableField(value = "appCode")
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_card_type.card_type
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    @TableField(value = "cardType")
    private String cardType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service_card_type.actived
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    @TableField("actived")
    private Long actived;


}