package com.hcc.crest.entity;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;

@TableName("service")
public class ServiceCard {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.id
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    @TableId(value= "id",type = IdType.AUTO)
    private Long id;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.app_code
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private String appCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.app_name
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private String appName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.status
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.remark
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.image
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private String image;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column service.actived
     *
     * @mbg.generated Sun Jan 17 14:03:41 CST 2021
     */
    private Long actived;


    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getAppCode() {
        return appCode;
    }

    public void setAppCode(String appCode) {
        this.appCode = appCode;
    }

    public String getAppName() {
        return appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public Long getActived() {
        return actived;
    }

    public void setActived(Long actived) {
        this.actived = actived;
    }



}